#              Send spam to people using bots (Python3) and (Discord.py)
import discord
import asyncio
from discord.ext.commands import Bot, Greedy
from discord import User
from discord.ext import commands

class Spam(commands.Cog, name="Spam"):

	def __init__(self, bot):
		self.bot = bot

	@commands.command()
	@commands.is_owner()
	async def dmspam(self, ctx, userid: str, *message: str):
		time = 1
		dm = self.bot.get_user(int(userid))
		msg = ' '.join(message)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await dm.send(msg)
		await asyncio.sleep(time)
		await ctx.message.add_reaction('👌')


	@commands.command()
	@commands.is_owner()
	async def chspam(self, ctx, channel: str, *message: str):
		time = 1
		ch = self.bot.get_channel(int(channel))
		msg = ' '.join(message)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ch.send(msg)
		await asyncio.sleep(time)
		await ctx.message.add_reaction('👌')

def setup(bot):
	bot.add_cog(Spam(bot))
